# Setup Github Page
markdown: kramdown
permalink: pretty

#Pagination
paginate: 5
paginate_path: "/blog/page:num/"

#Site Properties
title: Zhenglong Yu (喻正龙)
baseUrl: "/blogs"
slogan: "KEEP FORWARD"
description: Welcome to My Blog

author:
    name: Zhenglong Yu (喻正龙)
    email: zhenglong.yu@outlook.com
    corpUrl: https://e.huawei.com
    corpName: Huawei Technologies Co., Ltd.

github:
    repo: https://github.com/Ethan-Yu/blogs.git
    home: https://github.com/Ethan-Yu


