# Setup Github Page
markdown: kramdown
permalink: pretty

#Pagination
paginate: 5
paginate_path: "/blog/page:num/"

#Site Properties
title: Zhenglong Yu (喻正龙)
blog: 博客
title_tags: 标签
aboutme: 关于我
baseUrl: "/blogs"
slogan: "KEEP FORWARD"
description: 欢迎到来我的博客

# Disqus Information
disqus:
    shortname: zhenglong-yu
    url: https://zhenglong-yu.disqus.com

author:
    name: Zhenglong Yu (喻正龙)
    email: zhenglong.yu@qq.com
    corpUrl: https://e.huawei.com
    corpName: Huawei Technologies Co., Ltd.

github:
    repo: https://github.com/Ethan-Yu/blogs.git
    home: https://github.com/Ethan-Yu


